name: my workflow
on:
  push:
    tags:
      - "release/*"

jobs:
  build:
    name: hello github action
    runs-on: ubuntu-20.04
    steps:
      - name: checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      # - name: Compress build files
      #   run: tar -czvf build.tar.gz ./build/*

      # - name: Copy compress file to remote
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: build.tar.gz
      #     remote: build.tar.gz
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASSWORD }}
