name: my workflow
on: [push]

jobs:
  build:
    name: hello github action
    runs-on: ubuntu-20.04
    steps:
      - name: checkout source code
        uses: actions/checkout@master

      - name: echo Hello
        run: echo "Hello"
